### PR TITLE
Bump bcrypt library version from 0.7.0 to 0.9.0

### PR DESCRIPTION
**Pull request by meamuri**
Changes:
* bump at.favre.lib/bcrypt to 0.9.0

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the updates. Could you split the CI fix into another commit (and it's fine just to remove the JDK version I think, since Travis has updated their default JDK version), and remove the version and copyright changes? Version changes shouldn't be part of a PR, and PRs should be focused on a single change.

**Comment by meamuri** [comment]
Sorry for "dirty" work: I've sent second pull request with more clear commit history and focus just on the bcrypt library and ci.
I want to close this request and move conversation to #13

**Comment by weavejester** [comment]
Why did you open a new PR with the same changes, instead of changing the commits in this one?

Ah, and I see I wrote "commit" in my previous comment when I meant "PR". Sorry about that. Could I have the CI fix and the update in separate PRs? Or if you want I can just make all the changes myself this weekend.

**Comment by meamuri** [comment]
I've cleaned up history for this branch.

I'll use the #13 for ci fix updates

**Pull request closed without merging**
